Repository ckeditor/ckeditor5, pull requests merged in 2019-11, with the labels that each got.

#5679 i/5677: Updated the styles listing in the "Content styles" guide
  docs/builds/guides/integration/content-styles.md
Labels: type:sub-pr

#5621 Updated the CKEditor 4 migration guide
  docs/builds/guides/migrate.md
Labels: status:review-, type:docs

#5701 i/5696: Enabled style linter
  .stylelintrc
  docs/assets/snippet-styles.css
  package.json
  scripts/switch-to-dev-dev.sh
  yarn.lock
Labels: status:review-
